version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo "Installing dependencies..."
      - yarn install
  build:
    commands:
      - echo "Zipping deployment package..."
      - yarn run tsc
      - cd dist
      - zip -r deployment_package.zip dist
      # - cd lib
      # - zip -r9 ../deployment_package.zip .
      # - cd ..
      # - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name DraggbleFunction --zip-file fileb://deployment_package.zip
      - echo "DONE!!"